#
# Makefile.linux
#

CFLAGS	= -Wall -O2 -fsigned-char
CPPFLAGS= $(CFLAGS) -std=c++0x

OBJS	= main.o z80computer.o z80.o z80memory.o z80ports.o console.o ramdisk.o

all: cpmemu cpmdisk

cpmemu: $(OBJS)
	g++ -o $@ $(OBJS)

cpmdisk: cpmdisk.c
	gcc -Wall -O -o $@ $<

clean:
	rm -f $(OBJS) cpmemu cpmdisk
